FROM python:3.9

WORKDIR /app
COPY ./requirements.txt requirements.test.txt .
RUN pip install --no-cache-dir --upgrade -r requirements.txt -r requirements.test.txt
COPY . .
CMD ["pytest", "-q", "--tb=short", "--disable-warnings"]
